#!/usr/bin/env zsh
alias k=kubectl
alias xsc="xclip -selection clipboard"
alias setupproxyman="set -a && source \"/Users/arielbenichou/.proxyman/proxyman_env_automatic_setup.sh\" && set +a"
alias syncnetworx="sh ~/work/scripts/rsync_networx.sh"
alias upenv="sh ~/work/scripts/upenv.sh"
alias myip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias git-ssh='git remote set-url origin "$(git remote get-url origin | sed -E '\''s,^https://([^/]*)/(.*)$,git@\1:\2,'\'')"'
alias git-https='git remote set-url origin "$(git remote get-url origin | sed -E '\''s,^git@([^:]*):/*(.*)$,https://\1/\2,'\'')"'
