#!/usr/bin/env zsh
alias fd=fdfind
alias bat=batcat
alias vim=nvim
alias k=kubectl
alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias todo="glow ~/TODO.md"
alias todoe="nvim ~/TODO.md"
alias setupproxyman="set -a && source \"/Users/arielbenichou/.proxyman/proxyman_env_automatic_setup.sh\" && set +a"
alias syncnetworx="sh ~/work/scripts/rsync_networx.sh"
alias gitpty="prettier --write $(git diff --name-only --diff-filter d | xargs)"
alias myip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
