#!/usr/bin/env zsh
addToPath() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$PATH:$1
    fi
}

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

addToPathFront $HOME/.local/.npm-global/bin
addToPathFront $HOME/.local/n/bin/
addToPathFront $HOME/.local/bin
addToPathFront $HOME/.local/scripts
addToPathFront $HOME/.bun/bin
addToPathFront $HOME/Library/premake-5.0.0-beta2-macOS/
addToPathFront $HOME/Library/callGraph/

addToPathFront $HOME/.rbenv/versions/2.7.5/bin
addToPathFront $HOME/work/networx-frontend/tooling/kaizoku/kaizoku
addToPathFront $(go env GOPATH)/bin
addToPathFront $HOME/.zvm/self
addToPath $HOME/.zvm/bin
